# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6620e378dd1e2816bcd88389038886d5580bfbf7c8780161034f4b04b1a249b91841b2e9593fbb02531d5dd563b5e89236768a57575abd00417b7d98ad47e22

test:
  secret_key_base: 091087ab7a7572c2d05dc1d486643b0f44f3422db8b4bda7695099f082b1825edc3ee435410a3f647b280e92974435bc7165a01be7c6179dee22f1419e750c9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
